
services:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: writteplataformdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    mem_limit: 512m

volumes:
  mysql-data:
